#!/usr/bin/env python3
# protoc-gen-easyrpc-csharp: emit strong-typed client + server hint (REST paths).
import sys
from google.protobuf.compiler import plugin_pb2 as plugin

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            name=m.name or ''
            path=rest_path(m) or '/%s.%s/%s' % (pkg, svc.name, name)
            out.append((svc.name, name, path, m.server_streaming, m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out

def rest_path(m):
    opts=m.options
    if not opts: return None
    try:
        raw=opts.SerializeToString(); pos=0
        while pos < len(raw):
            tag,pos=readvar(raw,pos); field=tag>>3; wt=tag&7
            if wt==2:
                ln,pos=readvar(raw,pos); val=raw[pos:pos+ln]; pos+=ln
                if field==72295728:
                    p=parse_rule(val)
                    if p: return p
            elif wt==0: _,pos=readvar(raw,pos)
            elif wt==5: pos+=4
            elif wt==1: pos+=8
    except Exception:
        return None
    return None

def readvar(b,i):
    v=0;s=0
    while True:
        if i>=len(b): return v,i
        x=b[i]; i+=1; v|=(x&0x7f)<<s; s+=7
        if not (x&0x80): break
    return v,i

def parse_rule(d):
    i=0
    while i<len(d):
        tag,i=readvar(d,i); field=tag>>3; wt=tag&7
        if wt==2:
            ln,i=readvar(d,i); val=d[i:i+ln].decode(); i+=ln
            if field in (2,4,3,6): return val
        elif wt==0:
            _,i=readvar(d,i)
        elif wt==5: i+=4
        elif wt==1: i+=8
    return None

def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        L=[]
        L.append('// Code generated by protoc-gen-easyrpc-csharp. DO NOT EDIT.')
        L.append('using System;')
        L.append('using System.Collections.Generic;')
        L.append('using System.Threading.Tasks;')
        L.append('using EasyRpc;')
        L.append('using Easyrpc.Conformance.V1;')
        L.append('using Google.Protobuf;')
        L.append('')
        L.append('namespace EasyRpc {')
        L.append('  public class ConformanceServiceClient {')
        L.append('    private readonly Transport _t;')
        L.append('    public ConformanceServiceClient(Transport t) { _t = t; }')
        L.append('')
        for (svc,name,path,ss,it,ot) in ms:
            if ss:
                L.append('    public async IAsyncEnumerable<%s> %s(%s req) {' % (ot, camel(name), it))
                L.append('      var stream = await _t.OpenStream(new Request { Url = "%s", Body = req.ToByteArray() });' % path)
                L.append('      await foreach (var m in stream) { yield return %s.Parser.ParseFrom(m); }' % ot)
                L.append('    }')
            else:
                L.append('    public async Task<%s> %s(%s req) {' % (ot, camel(name), it))
                L.append('      var res = await _t.Send(new Request { Url = "%s", Body = req.ToByteArray() });' % path)
                L.append('      if (res.Error != null) throw res.Error;')
                L.append('      return %s.Parser.ParseFrom(res.Body);' % ot)
                L.append('    }')
            L.append('')
        L.append('  }')
        L.append('}')
        content='\n'.join(L)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc.cs', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

def camel(s): return s[:1].lower()+s[1:]
if __name__=='__main__': main()
