#!/usr/bin/env python3
# protoc-gen-easyrpc-csharp: emit <file>_easyrpc.cs with a method table.
import sys
from google.protobuf.compiler import plugin_pb2 as plugin

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            out.append((svc.name, m.name or '', f'/{pkg}.{svc.name}/{m.name}', m.server_streaming))
    return out

def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        pkg_parts='.'.join(w.title() for w in (f.package or 'easyrpc').split('.'))
        lines=['// Code generated by protoc-gen-easyrpc-csharp. DO NOT EDIT.',
               'using System.Collections.Generic;','namespace EasyRpc {','  public class EasyRpcMethod { public string Service; public string Name; public string Path; public bool ServerStream; public EasyRpcMethod(string s,string n,string p,bool ss){Service=s;Name=n;Path=p;ServerStream=ss;} }',
               '  public static class EasyRpcMethods {','    public static readonly List<EasyRpcMethod> Specs = new List<EasyRpcMethod>() {']
        for (svc,name,path,ss) in ms:
            sflag = 'true' if ss else 'false'
            lines.append('      new EasyRpcMethod("%s","%s","%s",%s),' % (svc, name, path, sflag))
        lines.append('    };')
        lines.append('  }')
        lines.append('}')
        content='\n'.join(lines)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc.cs', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

if __name__=='__main__': main()
