// Code generated by protoc-gen-easyrpc-csharp. DO NOT EDIT.
using System.Collections.Generic;
namespace EasyRpc {
  public class EasyRpcMethod { public string Service; public string Name; public string Path; public bool ServerStream; public EasyRpcMethod(string s,string n,string p,bool ss){Service=s;Name=n;Path=p;ServerStream=ss;} }
  public static class EasyRpcMethods {
    public static readonly List<EasyRpcMethod> Specs = new List<EasyRpcMethod>() {
      new EasyRpcMethod("ConformanceService","Health","/easyrpc.conformance.v1.ConformanceService/Health",false),
      new EasyRpcMethod("ConformanceService","Echo","/easyrpc.conformance.v1.ConformanceService/Echo",false),
      new EasyRpcMethod("ConformanceService","Count","/easyrpc.conformance.v1.ConformanceService/Count",true),
      new EasyRpcMethod("ConformanceService","Fail","/easyrpc.conformance.v1.ConformanceService/Fail",false),
    };
  }
}