// Code generated by protoc-gen-easyrpc-csharp. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using EasyRpc;
using Easyrpc.Conformance.V1;
using Google.Protobuf;

namespace EasyRpc {
  public class ConformanceServiceClient {
    private readonly Transport _t;
    public ConformanceServiceClient(Transport t) { _t = t; }

    public async Task<HealthResponse> health(HealthRequest req) {
      var res = await _t.Send(new Request { Url = "/easyrpc.conformance.v1.ConformanceService/Health", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return HealthResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<EchoResponse> echo(EchoRequest req) {
      var res = await _t.Send(new Request { Url = "/easyrpc.conformance.v1.ConformanceService/Echo", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return EchoResponse.Parser.ParseFrom(res.Body);
    }

    public async IAsyncEnumerable<CountResponse> count(CountRequest req) {
      var stream = await _t.OpenStream(new Request { Url = "/easyrpc.conformance.v1.ConformanceService/Count", Body = req.ToByteArray() });
      await foreach (var m in stream) {
        yield return CountResponse.Parser.ParseFrom(m);
      }
    }

    public async Task<FailResponse> fail(FailRequest req) {
      var res = await _t.Send(new Request { Url = "/easyrpc.conformance.v1.ConformanceService/Fail", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return FailResponse.Parser.ParseFrom(res.Body);
    }

  }
}